# -*- coding: utf-8 -*-
"""3_Model_Random_Forest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UVVOVejyrXqgNBbahiwvSx4TK7L-sw3r
"""

import pandas as pd
import requests
import io
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
import numpy as np
import os
import joblib
#PARAMETERS before launching
#define if we should keep the part "X_test_challenge" from the loaded file or ignore it
Ignore_X_test_challenge = True
isUseJoblib = True
FilePath="/Drive/My Drive/"


# Reading the downloaded content and turning it into a pandas dataframe
def get_ypred_proba(df):
    df['description']=df['description'].fillna("")
    df['desi_words_vs_unique']=df['desi_words_vs_unique'].fillna(0)
    df['desi_word_unique_percent']=df['desi_word_unique_percent'].fillna(0)
    df['descri_words_vs_unique']=df['descri_words_vs_unique'].fillna(0)
    df['descri_word_unique_percent']=df['descri_word_unique_percent'].fillna(0)
    
    if (isUseJoblib):
      clf1 = joblib.load('randomforest85000.joblib')
    else:
      clf1 = RandomForestClassifier(max_features ='sqrt', n_jobs = -1,n_estimators = 500)
      clf1.fit(X_train, y_train)
    
    y_pred = clf1.predict(X_test)
    ypred_proba = clf1.predict_proba(X_test)
    return ypred_proba

